// Extractor registration list shared by JavGuru, Javseen and XXXParodyHD.
// Order matters where two extractors match the same host (e.g. StreamTape
// before StreamTAPE) - keep the sequence stable.
package com.kraptor

import com.lagradost.cloudstream3.plugins.BasePlugin
import com.lagradost.cloudstream3.plugins.Plugin
import com.lagradost.cloudstream3.extractors.StreamTape
import com.lagradost.cloudstream3.extractors.EmturbovidExtractor
import com.lagradost.cloudstream3.extractors.DoodPmExtractor
import com.lagradost.cloudstream3.extractors.VidStack
import com.lagradost.cloudstream3.extractors.Voe
import com.lagradost.cloudstream3.utils.ExtractorApi

fun BasePlugin.registerSharedExtractors(first: List<ExtractorApi> = emptyList()) {
    first.forEach { registerExtractorAPI(it) }
    listOf(
        StreamTape(),
        StreamTapeNet(),
        StreamTapeXyz(),
        Turboplayers(),
        DoodStream(),
        DoodDoply(),
        DoodVideo(),
        Ds2Play(),
        d000d(),
        VidHidePro(),
        VidHidePro1(),
        VidHidePro2(),
        VidHidePro3(),
        VidHidePro4(),
        VidHidePro6(),
        VidHidePro7(),
        VidhideVIP(),
        CloudWish(),
        Dooood(),
        Javlion(),
        Dhcplay(),
        Smoothpre(),
        Dhtpre(),
        Peytonepre(),
        Movearnpre(),
        Dintezuvio(),
        Streamwish(),
        Streamhihi(),
        Javsw(),
        swhoi(),
        Javmoon(),
        MixDropis(),
        Javclan(),
        Javggvideo(),
        EmturbovidExtractor(),
        DoodPmExtractor(),
        VidNest(),
        HgLink(),
        RyderJet(),
        UpnsOnline(),
        EmbedSeek(),
        VipSeekPlayer(),
        EasyVidPlayer(),
        VipEasyVidPlayer(),
        MyCloudZ(),
        VidStack(),
        StbP2P(),
        Playerupnone(),
        Turtleviplay(),
        Turboviplay(),
        Vidguardto(),
        MixDropAG(),
        MixDropMy(),
        Player4Me(),
        Vip4me(),
        RPMShare(),
        Playmogo(),
        Voe(),
        Stape(),
        StreamTAPE(),
        ShaveTape(),
        Watchadsontape(),
        Lancewhoisdifficult(),
        Javlesbians(),
        LULUSTREAM(),
        LULUVDO(),
        LULUVDOO(),
        LULUPVP(),
        LULUDLC(),
        LULU0(),
        LULUX08(),
        javclan(),
        Stevenfamilyedge(),
        KPFilemoonSx(),
        KPFilemoonIn(),
        KPFilemoonLink(),
        KPFilemoonWf(),
        KPFilemoonEu(),
        KPFilemoonArt(),
        KPFilemoonNl(),
        KPCinegrab(),
        KPMoonmov(),
        KPNineSixAr(),
        KPKerapoxy(),
        KPFurher(),
        KPOneAzayf9w(),
        KPEightOneU6xl9d(),
        KPSmdfs40r(),
        KPC1z39(),
        KPBf0skv(),
        KPZ1ekv717(),
        KPL1afav(),
        KPTwoTwoTwoi8x(),
        KPEightMhlloqo(),
        KPF51rm(),
        KPXcoic(),
        KPBoosteradx(),
        KPStreamlyplayer(),
        KPStreamlyplayero(),
        KPBysewihe(),
        KPByselapuix(),
        KPEmbedplaybyse(),
        KPSb1254w9megshle(),
        KPMoflixStream(),
        KPBysezoxexe(),
        KPF16px(),
        KPBysesayeveum(),
        KPBysetayico(),
        KPBysevepoin(),
        KPBysezejataos(),
        KPBysekoze(),
        KPBysesukior(),
        KPBysejikuar(),
        KPBysefujedu(),
        KPBysedikamoum(),
        KPBysebuho(),
        KPByseSx(),
        KPByseqekaho(),
        Playmate(),
    ).forEach { registerExtractorAPI(it) }
}
